baseURL = "https://www.wingsxdu.com/"
staticDir = "static"
title = "beihai"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 4              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = "beihai"      # disqus_shortname
googleAnalytics = "UA-148836314-1"      # UA-XXXXXXXX-X
# copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓
enableGitInfo = true

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # Default language to use
[languages.zh-cn]
  languageCode = "zh-cn"

[author]                  # essential                     # 必需
  name = "beihai"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
  [[menu.main]]
  name = "关于博主"
  weight = 20
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "浏览博客"
  weight = 30
  identifier = "post"
  url = "/post/"
#[[menu.main]]
#  name = "分类标签"
#  weight = 40
#  identifier = "tags"
#  url = "/tags/"
[[menu.main]]
  name = "分类标签"
  weight = 40
  identifier = "categories"
  url = "/categories/"
  [[menu.main]]
  name = "旧站迁移"
  weight = 50
  identifier = "migrate"
  url = "/migrate/"


[params]
  since = "2018"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary
  mainSections = ["post"]

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "北海"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Golang", "Go", "back-end", "后端", "分布式"]
  description = "追求 源于热爱"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"
  moreMeta = true
  showAuthorInfo = false

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  # tencent_analytics = ""    # Tencent Analytics
  baidu_push = true        # baidu push                  # 百度
  baidu_analytics = "d9caa672b116c39e151b0da7c758ad88"      # Baidu Analytics

  # forkMeOnGithub = "https://github.com/wingsxdu"

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = true
    appId = 'xOfRpu7vOLeiw37zSFcRJcM1-gzGzoHsz'
    appKey = 'VbWuMaUMcNBPpzjeaXX0KIJS'
    notify = false  # If you are using valine-admin(https://github.com/DesertsP/Valine-Admin) to notify users, do NOT enable this.
    verify = false # Verification code
    avatar = 'mm'
    placeholder = ''

  [params.search.google]    # google custom search, see https://cse.google.com
    enable = true
    id = "017584266070941033843:b2bcs9ip4y9"
    title = "Search"

   [params.publicCDN]# 启用公共CDN，需自行定义
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
    photoswipe = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.js" integrity="sha256-AC9ChpELidrhGHX23ZU53vmRdz3FhKaN9E28+BbcWBw=" crossorigin="anonymous"></script>'
    photoswipeUI = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js" integrity="sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=" crossorigin="anonymous"></script>'
    photoswipeCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.css" integrity="sha256-SBLU4vv6CA6lHsZ1XyTdhyjJxCjPif/TRkjnsyGAGnE=" crossorigin="anonymous">'
    photoswipeSKIN = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.css" integrity="sha256-c0uckgykQ9v5k+IqViZOZKc47Jn7KQil4/MP3ySA3F8=" crossorigin="anonymous">'

  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
    enable = true

  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  [params.gitInfo]
    gitRepo = "https://github.com/wingsxdu/blog"
    showCommitMessage = true
  [params.social]                                         # 社交链接
    a-email = "mailto:beihai@wingsxdu.com"
    g-github = "https://github.com/wingsxdu"
    h-weibo = "https://weibo.com/u/6120467917"
